site_name: SSH for dummies

pages:
- 'Home': index.md
- 'Server':
    - 'Installation': server_install.md
    - 'Konfiguration OpenSSH Server': server_konfiguration.md
- 'Client':
    - 'Schl체sselverwaltung': key_management.md
    - 'Schl체sselgenerierung': keygen.md
    - 'Passwort eines Schl체ssels 채ndern': change_password.md
    - 'Konfiguration des SSH Client': ssh_client.md
    - 'SSH Agent': ssh_agent.md
    - 'Port Weiterleitung': port_forwarding.md
- Autor: author.md

markdown_extensions:
- smarty
- toc:
    permalink: True
