site_name: SSH for dummies

pages:
- 'Home': index.md
- 'Server':
    - 'Installation': server_install.md
    - 'Konfiguration des ssh Daemon': sshd.md
- 'Client':
    - 'Schlüsselverwaltung': key_management.md
    - 'Schlüsselgenerierung': keygen.md
    - 'Konfiguration des SSH Client': ssh_client.md
    - 'SSH Agent': ssh_agent.md
    - 'Port Weiterleitung': port_forwarding.md
- Autor: author.md
